---
- name: Common for all
  hosts: all
  become: yes

  tasks:
    - name: Initial update yum cache
      yum:
        update_cache: yes

    - name: Add initial dependencies
      yum:
        name: 
          - sysstat
          - tree
        state: present