---
- name: Install Node Exporter on Linux Servers
  hosts: node
  become: true
  vars:
    node_exporter_version: "1.6.1"
    node_exporter_install_dir: "/usr/local/bin"

  tasks:
    - name: Create Node Exporter user
      ansible.builtin.user:
        name: "node_exporter"
        system: true
        shell: /usr/sbin/nologin

    - name: Download Node Exporter
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"
        mode: '0755'

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/tmp"
        remote_src: true

    - name: Copy Node Exporter binary to install directory
      ansible.builtin.copy:
        remote_src: yes
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_install_dir }}/node_exporter"
        mode: '0755'
        owner: "node_exporter"
        group: "node_exporter"

    - name: Create Node Exporter systemd service file
      ansible.builtin.template:
        src: "../configs/node_exporter.service.j2"
        dest: "/etc/systemd/system/node_exporter.service"
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Node Exporter service
      ansible.builtin.systemd:
        name: "node_exporter"
        enabled: true
        state: started

    - name: Clean up temporary files
      ansible.builtin.file:
        path: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"
        state: absent
      ignore_errors: true
    - name: Remove Node Exporter tarball
      ansible.builtin.file:
        path: "/tmp/node_exporter.tar.gz"
        state: absent
      ignore_errors: true
