---
- name: Install Prometheus
  hosts: prometheus
  become: yes
  vars:
    prometheus_version: "2.47.0"
    prometheus_install_dir: "/usr/local/bin"
    prometheus_config_dir: "/etc/prometheus"
    prometheus_data_dir: "/var/lib/prometheus"

  tasks:
    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Download Prometheus
      get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"

    - name: Extract Prometheus
      unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Prometheus binaries
      copy:
        remote_src: yes
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
        dest: "{{ prometheus_install_dir }}/prometheus"
        mode: '0755'

    - name: Move Promtool binary
      copy:
        remote_src: yes
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/promtool"
        dest: "{{ prometheus_install_dir }}/promtool"
        mode: '0755'

    - name: Create Prometheus user
      user:
        name: "prometheus"
        shell: /bin/false
        create_home: no

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "prometheus"
        group: "prometheus"
        mode: '0755'
      loop:
        - "{{ prometheus_config_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Move Prometheus config file
      template:
        src: "../configs/prometheus.yml.j2"
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
        mode: '0644'

    - name: Change ownership of Prometheus directories
      file:
        path: "{{ item }}"
        owner: "prometheus"
        group: "prometheus"
        recurse: yes
      loop:
        - "{{ prometheus_config_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Create Prometheus systemd service file
      template:
        src: "../configs/prometheus.service.j2"
        dest: /etc/systemd/system/prometheus.service
        mode: '0644'

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
