---
- name: Install Push Gateway
  hosts: push_gateway
  become: yes
  vars:

  tasks:
    - name: Install Push Gateway
      dnf:
        name: prometheus-pushgateway
        state: present

    - name: Start and enable Push gateway service
      systemd:
        name: prometheus-pushgateway
        state: started
        enabled: yes